### ISSUE TITLE
error trying to install on Android 

### ISSUE THREAD

**Issue by moltra** [moltra/Auto-GPT-android#1]
Using Termux on Android S21

`~/Auto-GPT $ pip install -r requirements.txt
Collecting beautifulsoup4 (from -r requirements.txt (line 1))
  Downloading beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━ 143.0/143.0   808.2 kB/s eta 0:00:00
                    kB
Collecting colorama==0.4.6 (from -r requirements.txt (line 2))
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting openai==0.27.2 (from -r requirements.txt (line 3))
  Downloading openai-0.27.2-py3-none-any.whl (70 kB)
     ━━━━━━━━━━━━━━━ 70.1/70.1 kB 604.9 kB/s eta 0:00:00
Collecting playsound==1.2.2 (from -r requirements.txt (line 4))
  Downloading playsound-1.2.2-py2.py3-none-any.whl (6.0 kB)
Collecting python-dotenv==1.0.0 (from -r requirements.txt (line 5))
  Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting pyyaml==6.0 (from -r requirements.txt (line 6))
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━ 125.0/125.0 kB 1.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting readability-lxml==0.8.1 (from -r requirements.txt (line 7))
  Downloading readability_lxml-0.8.1-py3-none-any.whl (20 kB)
Collecting requests (from -r requirements.txt (line 8))
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━ 62.8/62.8 kB 169.5 kB/s eta 0:00:00
Collecting tiktoken==0.3.3 (from -r requirements.txt (line 9))
  Downloading tiktoken-0.3.3.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gTTS==2.3.1 (from -r requirements.txt (line 10))
  Downloading gTTS-2.3.1-py3-none-any.whl (28 kB)
Collecting docker (from -r requirements.txt (line 11))
  Downloading docker-6.0.1-py3-none-any.whl (147 kB)
     ━━━━━━━━━━━━━━━ 147.5/147.5 kB 1.3 MB/s eta 0:00:00
Collecting duckduckgo-search (from -r requirements.txt (line 12))
  Downloading duckduckgo_search-2.8.6-py3-none-any.whl (30 kB)
Collecting google-api-python-client (from -r requirements.txt (line 13))
  Downloading google_api_python_client-2.85.0-py2.py3-none-any.whl (11.2 MB)
     ━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 2.0 MB/s eta 0:00:00
Collecting pinecone-client==2.2.1 (from -r requirements.txt (line 14))
  Downloading pinecone_client-2.2.1-py3-none-any.whl (177 kB)
     ━━━━━━━━━━━━━━━ 177.2/177.2 kB 4.7 MB/s eta 0:00:00
Collecting redis (from -r requirements.txt (line 15))
  Downloading redis-4.5.4-py3-none-any.whl (238 kB)
     ━━━━━━━━━━━━━━━ 238.9/238.9 kB 4.1 MB/s eta 0:00:00
Collecting orjson (from -r requirements.txt (line 16))
  Downloading orjson-3.8.10.tar.gz (836 kB)
     ━━━━━━━━━━━━━━━ 836.5/836.5 kB 3.5 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Collecting maturin<2,>=0.13
        Downloading maturin-0.14.17.tar.gz (177 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.9/177.9 kB 708.8 kB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: maturin
        Building wheel for maturin (pyproject.toml): started
        Building wheel for maturin (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for maturin (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [32 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-aarch64-cpython-311
            creating build/lib.linux-aarch64-cpython-311/maturin
            copying maturin/__init__.py -> build/lib.linux-aarch64-cpython-311/maturin
            copying maturin/__main__.py -> build/lib.linux-aarch64-cpython-311/maturin
            copying maturin/import_hook.py -> build/lib.linux-aarch64-cpython-311/maturin
            running egg_info
            creating maturin.egg-info
            writing maturin.egg-info/PKG-INFO
            writing dependency_links to maturin.egg-info/dependency_links.txt
            writing requirements to maturin.egg-info/requires.txt
            writing top-level names to maturin.egg-info/top_level.txt
            writing manifest file 'maturin.egg-info/SOURCES.txt'
            reading manifest file 'maturin.egg-info/SOURCES.txt'
            reading manifest template 'MANIFEST.in'
            writing manifest file 'maturin.egg-info/SOURCES.txt'
            running build_ext
            running build_rust
            error: can't find Rust compiler

            If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

            To update pip, run:

                pip install --upgrade pip

            and then retry package installation.

            If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for maturin
      Failed to build maturin
      ERROR: Could not build wheels for maturin, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
`

**Comment by OSohaii** [comment]
Consegui chegar até só até o Puglin orjson
